### ISSUE TITLE
Implement new version of Wasp compiler (analyzer)

### ISSUE THREAD

**Issue by Martinsos** [wasp-lang/wasp#299]
Wasp compiler consists of 2 phases: Analyzer (Parser) and Generator. Analyzer (Parser) parses Wasp code and creates AST which is then provided to Generator which generates JS code based on it.

Right now, Parser is implemented using parser combinators and there is lot of boilerplate and complexity in the code. This means language is very "ad-hoc", which was great for fast prototyping, but makes it harder to build serious tooling on top of it as we have to do a lot of things manually. Check here for more details: https://github.com/wasp-lang/wasp/issues/109 .

This is why we are implementing a new version of Parser, called Analyzer, which uses formal grammar and lexer and parser generators (Alex and Happy), which means we write less code and get more out of it. This means codebase is easier to maintain and modify! This effort is being lead by @craigmc08 , and you can find the code committed so far under the `Analyzer` haskell module. Once new `Analyzer` is stable, it will replace `Parser` while still using existing `Generator`.

You can find documentation describing new formal grammar under https://github.com/wasp-lang/wasp/tree/master/waspc/docs/wasplang .

New code (`Analyzer`): https://github.com/wasp-lang/wasp/tree/master/waspc/src/Analyzer .

Relevant PRs so far, from oldest to newest:
- https://github.com/wasp-lang/wasp/pull/257
- https://github.com/wasp-lang/wasp/pull/274
- https://github.com/wasp-lang/wasp/pull/289
- https://github.com/wasp-lang/wasp/pull/300

TODO:
- [x] Implement skeleton of MVP of Analyzer, with placeholders for Parser, TypeChecker and Evaluator.
- [x] Implement MVP of Parser.
- [x] Implement MVP of TypeChecker.
- [x] Implement MVP of Evaluator.
- [x] Get MVP of Analyzer working as a whole, try connecting it with Generator if possible at this stage.
- [x] Get Analyzer from MVP to support everything Wasp currently supports.
- [x] Replace old Parser with Analyzer and drop old code.
- [ ] Implement advanced features like multiple files and similar (everything that was described in latex doc but wasn't implemented yet).

**Comment by Martinsos** [comment]
So, right now we have MVP done, with all parts in and working: Parser, TypeChecker, Evaluator. However, there are features missing, and currently our Analyzer is using mock types, not the ones from Wasp.hs.

Here goes the plan to bring Analyzer to the stage where it can replace current Parser:
1. Ensure that each declaration is packed with its name, if it has one. Maybe this is already ok but I am not sure, we should check and make it work if it's not.
  What does this mean? If we have `app MyApp ...` that has property `defaultPage` of type `page` and is set to `HomePage` where we have `page HomePage ...`, then when generator receives the AST to work with, it will need to know the name of the declaration that `defaultPage` is pointing to. And I am not sure if that is currently part of AST in this case or not.
2. Ensure that nameless declarations, like `dependencies { ... }` are supported.
3. Use types from Wasp.hs in Analyzer! Maybe best to create a new module, Wasp.AST, and go from there?
  Update StdTypeDefinitions.hs and Delete Evaluator.Types . As a result, Generator might need updating also, to work with these new types? But then it will stop working with old types. A bit tricky. Maybe we can implement adapter from new WaspAST to existing Wasp, so that Generator is reused?

This should be enough to get Analyzer working end to end!

Next, we want to get it to the same level as current implementation is:

4. Enable referencing of declarations described below the current location in the source code.
  Start from Evaluator.hs.
5. New syntax is a bit different from older syntax -> for example, we don't have special syntax for `route` any more. We should either add that syntax to compiler, or we should update the docs / examples.
6. Other -> I am sure we missed some stuff, but that will be easier to identify once we give it a try.
7. Remove old Parser and let Analyzer do all the work.

This is it, Analyzer is in action and is being used!

Finally, there are further improvements to be made:

8. Add quoters to type definitions. -> refactoring
  There is TODO in Analyzer.TypeChecker.Internal. Another in Analyzer.TypeChecker.AST. One more in Analyzer.TypeDefinitions.Internal.
9. Improve type error reporting
  9.1. Report multiple errors
  9.2. Report position
  9.3. Make user-readable messages for all errors, especially for unification/weaken errors since they are not that understandable.
  TODO for this in TypeError.hs
10. Advanced: support for splitting Wasp into multiple files.
11. Share same AST between Parser and TypeChecker? This is a refactoring / optimization and can be done later

**Comment by Martinsos** [comment]
Closing this one, since new version of Analyzer got merged!

Advanced features are still outstanding, but they are labeled with `analyzer` label, so it is best to track them that way -> I will close this one.
