### ISSUE TITLE
[example/waspello] Add more Trello features to Waspello

### ISSUE THREAD

**Issue by matijaSos** [wasp-lang/wasp#337]
There is a myriad of Trello features that Wasp doesn't support yet, e.g. multiple boards/workspaces, user collaboration, search, .... We can use this thread to list them, propose ideas and discuss which ones to implement next!

Some possibly good candidates:
- [ ] User collaboration - multiple can users can edit the same board
- [ ] search - user can search for a specific list/card
- [ ] card menu - when clicked on the right side of the card the quick menu opens (see in Trello)
- [ ] card detailed view - when clicked on the card open "full" card view
